/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Logic.Usuario;
import java.awt.Color;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author Alumnos UTJ CCD
 */
public class FRegistrarse extends javax.swing.JFrame {

    /**
     * Creates new form FRegistrarse
     */
    Usuario usuario = new Usuario();
    public FRegistrarse() {
        initComponents();
        imagen();
        jcbAño.setModel(Años());
        jcbDia.setModel(Dias());
    }

    public boolean verificardatos(){
        boolean v = false;
        if(!"".equals(jtfNombre.getText())){
            if(!"".equals(jtfApellidos.getText())){
                if(!"".equals(jtfDireccion.getText())){
                    if(!"".equals(jtfTelefono.getText())){
                        try{
                        usuario.setTelefono(Integer.parseInt(jtfTelefono.getText())); 
                        if(!"".equals(jtfUsuario.getText())){
                            if (!"".equals(jpfContraseña.getText())){
                                v = true;
                            }else{
                               jpfContraseña.setBackground(new java.awt.Color(255,255,204));
                               jlerror1.setText("Campo obligatorio");
                            }
                        }else{
                        jtfUsuario.setBackground(new java.awt.Color(255,255,204));
                        jlerror1.setText("Campo obligatorio");
                        v = false;
                        }
                        }catch(NumberFormatException ex){
                         jtfTelefono.setBackground(new java.awt.Color(255,255,204));
                         jlerror1.setText("Utilice valores númericos");
                         v = false;
                        }
                    }else{
                        jtfTelefono.setBackground(new java.awt.Color(255,255,204));
                        jlerror1.setText("Campo obligatorio");
                        v = false;
                    }
                }else{
                    jtfDireccion.setBackground(new java.awt.Color(255,255,204));
                    jlerror1.setText("Campo obligatorio");
                    v = false;
                }
            }else{
                jtfApellidos.setBackground(new java.awt.Color(255,255,204));
                jlerror1.setText("Campo obligatorio");
                v = false;
            }
        }else{
        jtfNombre.setBackground(new java.awt.Color(255,255,204));
        jlerror1.setText("Campo obligatorio");
        v = false;
        }
        return v;
    }
    private DefaultComboBoxModel Años(){
        DefaultComboBoxModel año = new DefaultComboBoxModel();
        for(int num=1980;num<2005;num+=1){
             año.addElement(num);
        }
        return año;
    }
    private DefaultComboBoxModel Dias(){
        DefaultComboBoxModel dia = new DefaultComboBoxModel();
        for(int num=1;num<=31;num+=1){
            dia.addElement(num);
        }
        return dia;
    }
    
    public  void imagen(){
        ImageIcon logo = new ImageIcon(getClass().getResource("/Imagenes/LogoMin.jpg"));
        jlLogo.setIcon(new ImageIcon(logo.getImage().getScaledInstance(jlLogo.getWidth(),jlLogo.getHeight(), Image.SCALE_SMOOTH)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jtfDireccion = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        jpfContraseña = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jbRegistrar = new javax.swing.JButton();
        jbRegresar = new javax.swing.JButton();
        jlerror1 = new javax.swing.JLabel();
        jcbAño = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbDia = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Usuarios");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel13.setText("Bienvenido");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
        jPanel1.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 90));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 110));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nombre(s)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jtfNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 180, -1));

        jtfApellidos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(jtfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, -1));

        jtfDireccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(jtfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, -1));

        jtfTelefono.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 180, -1));

        jtfUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 180, -1));

        jpfContraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jpfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 180, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Año");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Mes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Día");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jbRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 100, 30));

        jbRegresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbRegresar.setText("Regresar");
        jbRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jbRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 100, 30));

        jlerror1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jlerror1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jlerror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 410, 20));

        jcbAño.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbAño.setAutoscrolls(true);
        jcbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAñoActionPerformed(evt);
            }
        });
        jPanel1.add(jcbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jcbMes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(jcbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jcbDia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jcbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDiaActionPerformed(evt);
            }
        });
        jPanel1.add(jcbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Nacimiento");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegresarActionPerformed
        FLogin fl = new FLogin();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbRegresarActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        if(jtfNombre.equals("")){
            jtfNombre.setBackground(new java.awt.Color(255,255,204));
            jlerror1.setText("Campo obligatorio");
            
        }else{
            jtfNombre.setBackground(Color.white);
            jlerror1.setText("");
            jtfApellidos.requestFocus();
        }
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidosActionPerformed
        if(jtfApellidos.equals("")){
            jtfApellidos.setBackground(new java.awt.Color(255,255,204));
            jlerror1.setText("Campo obligatorio");
        }else{
            jtfApellidos.setBackground(Color.white);
            jlerror1.setText("");
            jtfDireccion.requestFocus();
        }
        
    }//GEN-LAST:event_jtfApellidosActionPerformed

    private void jtfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDireccionActionPerformed
        if(jtfDireccion.equals("")){
            jtfDireccion.setBackground(new java.awt.Color(255,255,204));
            jlerror1.setText("Campo obligatorio");
        }else{
            jtfDireccion.setBackground(Color.white);
            jlerror1.setText("");
            jcbAño.requestFocus();
        }
    }//GEN-LAST:event_jtfDireccionActionPerformed

    private void jcbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAñoActionPerformed

    }//GEN-LAST:event_jcbAñoActionPerformed

    private void jcbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDiaActionPerformed

    private void jtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoActionPerformed
        if(jtfTelefono.equals("")){
            jtfTelefono.setBackground(new java.awt.Color(255,255,204));
            jlerror1.setText("Campo obligatorio");
        }else{
            jtfTelefono.setBackground(Color.white);
            jlerror1.setText("");
            jtfUsuario.requestFocus();
            try{
                usuario.setTelefono(Integer.parseInt(jtfTelefono.getText()));
                
            }catch(NumberFormatException ex){
                jtfTelefono.setBackground(new java.awt.Color(255,255,204));
                jlerror1.setText("Utilice valores númericos");
            }
        }
    }//GEN-LAST:event_jtfTelefonoActionPerformed

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        if(jtfUsuario.equals("")){
            jtfUsuario.setBackground(new java.awt.Color(255,255,204));
            jlerror1.setText("Campo obligatorio");
        }else{
            jtfUsuario.setBackground(Color.white);
            jlerror1.setText("");
            jpfContraseña.requestFocus();
        }
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jpfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfContraseñaActionPerformed
        if(jpfContraseña.equals("")){
            jpfContraseña.setBackground(new java.awt.Color(255,255,204));
            jlerror1.setText("Campo obligatorio");
        }else{
            jpfContraseña.setBackground(Color.white);
            jlerror1.setText("");
            jbRegistrar.requestFocus();
        }
    }//GEN-LAST:event_jpfContraseñaActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        FLogin fl = new FLogin();
        usuario.setNombre(jtfNombre.getText());
        usuario.setApellidos(jtfApellidos.getText());
        usuario.setDireccion(jtfDireccion.getText());
        usuario.setFechana(jcbAño.getSelectedItem()+"/"+jcbMes.getSelectedItem()+"/"+jcbDia.getSelectedItem());
        usuario.setNombUsuario(jtfUsuario.getText());
        usuario.setContraseña(jpfContraseña.getPassword().toString());
        if(verificardatos()== true){
        jlerror1.setText(usuario.RegistrarUsuario());
        fl.setUsu(jtfUsuario.getText());
        fl.setContra(jpfContraseña.getText());
        fl.returndatos();
        fl.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jbRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jbRegresar;
    private javax.swing.JComboBox<String> jcbAño;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlerror1;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
